### ISSUE TITLE
The action doesn't work in our project

### ISSUE THREAD

**Issue by akihironitta** [larsoner/circleci-artifacts-redirector-action#26]
First of all, thank you so much for creating this very useful action!

---

We're trying to utilise this action, but it doesn't work. Would it be possible for you to point out any possible causes making this action not working in our setting?

Following the `README.md`, I see its debug-level log by enabling `ACTIONS_STEP_DEBUG=true`, but I don't see any relevant information there:
- the log: https://gist.github.com/akihironitta/8ea4c5b51c3dfae94e100e4f63291d9f
- the job run: https://github.com/PyTorchLightning/pytorch-lightning/runs/6643967543?check_suite_focus=true

Our workflow file in master:
```yml
on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-20.04
    steps:
    - uses: larsoner/circleci-artifacts-redirector-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-path: 0/html/index.html
        circleci-jobs: build-Docs
        job-title: Check the rendered docs here!
```
https://github.com/PyTorchLightning/pytorch-lightning/blob/a6e9bc2943bf2c82036e31a4948bd8caa54957ee/.github/workflows/docs-link.yml

Our CircleCI job that generates artifacts:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a6e9bc2943bf2c82036e31a4948bd8caa54957ee/.circleci/config.yml#L162

Any help is welcome. Thank you in advance.
